#!/bin/bash

mvn clean compile package
docker build -t jbrilha/scc2425-tukano2:latest webapp/.
docker build -t jbrilha/scc2425-tukano2-blobs:latest blob-service/.
#docker build -t eervideirafct/scc2425-tukano2:latest webapp/.
#docker build -t eervideirafct/scc2425-tukano2-blobs:latest blob-service/.
#docker push eervideirafct/scc2425-tukano2:latest
#docker push eervideirafct/scc2425-tukano2-blobs:latest

kubectl delete all --all
kubectl apply -f k8s/secrets.yaml
kubectl apply -f k8s/persistent-volume.yaml
kubectl apply -f k8s/redis.yaml
kubectl apply -f k8s/postgres.yaml
kubectl apply -f k8s/tukano2-webapp.yaml
kubectl apply -f k8s/tukano2-blobs.yaml
kubectl apply -f k8s/ingress.yaml
kubectl rollout restart deployment

if [ "$1" == "local" ]; then
  minikube tunnel
fi
