#!/bin/bash

mvn clean compile package
docker build -t eduardoervideira/scc2425-tukano2:latest .

kubectl delete all --all
kubectl apply -f k8s/redis.yaml
kubectl apply -f k8s/postgres.yaml
kubectl apply -f k8s/persistent-volume.yaml
kubectl apply -f k8s/tukano2-webapp.yaml
kubectl rollout restart deployment
minikube ip
