apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano-webapp
  template:
    metadata:
      labels:
        app: tukano-webapp
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: tukano-webapp
          image: jbrilha/scc2425-tukano2:latest
          imagePullPolicy: Never
          env:
            - name: REDIS_KEY
              value: "joaoeddyREDIS"
            - name: REDIS_URL
              value: "redis-service"
            - name: SECRET
              value: "supersecret"
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "tukano"
            - name: POSTGRES_USER
              value: "joaoeddy"
            - name: POSTGRES_PASSWORD
              value: "joaoeddyCHANGELATER"
            - name: BLOBS_SERVICE_URL
              value: "tukano-blobs-service"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tukano-webapp-service
spec:
  type: NodePort
  selector:
    app: tukano-webapp
  ports:
    - port: 8080
      targetPort: 8080
