apiVersion: batch/v1
kind: CronJob
metadata:
  name: tukano-recommends
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - curl http://tukano-webapp-service:8080/webapp-2/rest/functions/recs
          restartPolicy: OnFailure
