apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blob-storage-pvc
spec:
  storageClassName: azure-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: azure-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi